const KEY='restart-dashboard-v1';
const todayKey=()=>new Date().toLocaleDateString('en-CA');
const initial={entries:{},projects:[{id:'default',name:'가벼운 실험',type:'experiment',created:todayKey()}],interruptions:[],recoveries:[],cycle:{goal:'',start:todayKey()}};
let selectedDate=todayKey(),calendarMonth=new Date(todayKey()+'T12:00'),data=migrate(load()),timer={remaining:600,running:false,id:null,startedAt:null},installPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return {...structuredClone(initial),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(initial)}}
function migrate(source){const next={...structuredClone(initial),...source};next.entries=next.entries||{};Object.values(next.entries).forEach(e=>{if(!Array.isArray(e.actions)){e.actions=e.keyAction?[{id:crypto.randomUUID(),text:e.keyAction,done:!!e.completed}]:[]}e.actions=e.actions.map((a,i)=>({id:a.id||crypto.randomUUID(),text:a.text||'',done:i===0?!!(a.done||e.completed):!!a.done}));e.keyAction=e.actions[0]?.text||e.keyAction||'';e.completed=!!e.actions[0]?.done});return next}
function mergeActions(older=[],newer=[]){const result=[],positions=new Map();[...older,...newer].forEach(a=>{const key=(a.text||'').trim().toLocaleLowerCase()||a.id;if(positions.has(key)){const i=positions.get(key);result[i]={...result[i],...a,done:!!(result[i].done||a.done)}}else{positions.set(key,result.length);result.push({...a,id:a.id||crypto.randomUUID()})}});return result.filter(a=>a.text)}
function mergeEntry(current,incoming,date){if(!current)return{...incoming,date};const incomingNewer=new Date(incoming.updatedAt||0)>new Date(current.updatedAt||0),newer=incomingNewer?incoming:current,older=incomingNewer?current:incoming,out={...older,...newer,date};out.actions=mergeActions(older.actions||[],newer.actions||[]);const textFields=['oneLine','learned','blocked','solved','nevertheless','aiHelp','tomorrowFirst'];textFields.forEach(k=>{if(!out[k])out[k]=older[k]||newer[k]||''});['mood','independence','motivation'].forEach(k=>{if(out[k]===null||out[k]==='')out[k]=older[k]??newer[k]??null});out.keyAction=out.actions[0]?.text||out.keyAction||'';out.completed=!!out.actions[0]?.done;out.started=!!(current.started||incoming.started);out.focusMinutes=Math.max(Number(current.focusMinutes)||0,Number(incoming.focusMinutes)||0);return out}
function combineText(a='',b=''){const left=String(a).trim(),right=String(b).trim();if(!left)return right;if(!right||left===right)return left;return `${left}\n\n${right}`}
function mergeWholeDay(destination,source,date){if(!destination)return{...structuredClone(source),date,updatedAt:new Date().toISOString()};const out={...destination,...source,date,updatedAt:new Date().toISOString()};out.actions=mergeActions(destination.actions||[],source.actions||[]);['oneLine','learned','blocked','solved','nevertheless','aiHelp','tomorrowFirst'].forEach(k=>out[k]=combineText(destination[k],source[k]));out.keyAction=out.actions[0]?.text||'';out.completed=!!out.actions[0]?.done;out.started=!!(destination.started||source.started);out.focusMinutes=(Number(destination.focusMinutes)||0)+(Number(source.focusMinutes)||0);out.mood=source.mood??destination.mood??null;out.independence=source.independence??destination.independence??null;out.motivation=source.motivation??destination.motivation??null;return out}
function hasDayContent(e){return!!((e.actions||[]).some(a=>a.text)||e.keyAction||e.focusMinutes||e.oneLine||e.learned||e.blocked||e.solved||e.nevertheless||e.aiHelp||e.tomorrowFirst||e.mood||e.independence||e.motivation)}
function uniqueBy(items,keyFn){const seen=new Set();return(items||[]).filter(item=>{const key=keyFn(item);if(seen.has(key))return false;seen.add(key);return true})}
function mergeData(current,imported){const incoming=migrate(imported),out=migrate(structuredClone(current));Object.entries(incoming.entries).forEach(([date,e])=>{out.entries[date]=mergeEntry(out.entries[date],e,date)});out.projects=uniqueBy([...(out.projects||[]),...(incoming.projects||[])],p=>p.id||p.name);out.interruptions=uniqueBy([...(out.interruptions||[]),...(incoming.interruptions||[])],x=>x.at);out.recoveries=uniqueBy([...(out.recoveries||[]),...(incoming.recoveries||[])],x=>`${x.interruptedAt}|${x.recoveredAt}`);if(!out.cycle?.goal&&incoming.cycle)out.cycle=incoming.cycle;return out}
function save(){localStorage.setItem(KEY,JSON.stringify(data));$('#saveState').textContent='자동 저장됨 · '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function dateOffset(n){const d=new Date();d.setDate(d.getDate()+n);return d.toLocaleDateString('en-CA')}
function blankEntry(date){return{date,workMode:'solo',projectId:data.projects[0]?.id||'',started:false,completed:false,focusMinutes:0,actions:[],mood:null}}
function entryFor(date){return data.entries[date]||blankEntry(date)}
function entry(){return entryFor(selectedDate)}
function renderDate(){const d=new Date(selectedDate+'T12:00'),isCurrent=selectedDate===todayKey(),isPast=selectedDate<todayKey();$('#todayLabel').textContent=d.toLocaleDateString('ko-KR',{year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined,month:'long',day:'numeric',weekday:'long'}).toUpperCase();$('#dateQuestion').innerHTML=isCurrent?'오늘은 무엇을<br><em>시작</em>할까요?':isPast?'이날 무엇을<br><em>했었나요?</em>':'이날 무엇을<br><em>할까요?</em>';$('#goToday').classList.toggle('current',isCurrent);$('#timerBtn').disabled=!isCurrent;$('#timerReset').disabled=!isCurrent;$('#interruptBtn').disabled=!isCurrent;$('.timer-panel').classList.toggle('date-locked',!isCurrent);$('#timerHint').textContent=isCurrent?'완성 말고, 착수':'선택한 날짜의 기록을 편집 중';renderCalendar()}
function renderCalendar(){const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth(),first=new Date(year,month,1,12),start=new Date(year,month,1-first.getDay(),12);$('#calendarMonthLabel').textContent=`${year}년 ${month+1}월`;$('#calendarGrid').innerHTML=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toLocaleDateString('en-CA'),e=data.entries[key],hasPlan=e?.actions?.some(a=>a.text)||e?.keyAction,hasDone=e?.actions?.some(a=>a.done)||e?.completed;return `<button type="button" data-date="${key}" class="${d.getMonth()!==month?'outside ':''}${key===todayKey()?'today ':''}${key===selectedDate?'selected ':''}${hasDone?'has-done':hasPlan?'has-plan':''}" aria-label="${d.toLocaleDateString('ko-KR')} 선택">${d.getDate()}</button>`}).join('')}
function moveDate(amount){const d=new Date(selectedDate+'T12:00');d.setDate(d.getDate()+amount);changeDate(d.toLocaleDateString('en-CA'))}
function changeDate(next){if(!next)return;if(next===selectedDate){$('#calendarPanel').classList.add('hidden');return}if(timer.running)toggleTimer();collect();selectedDate=next;calendarMonth=new Date(selectedDate+'T12:00');renderDate();renderProjects();hydrate();$('#calendarPanel').classList.add('hidden');toast(selectedDate===todayKey()?'오늘 기록으로 돌아왔습니다.':'선택한 날짜의 기록을 불러왔습니다.')}
function renderProjects(){const sel=$('#projectId');sel.innerHTML=data.projects.map(p=>`<option value="${p.id}">${escapeHtml(p.name)} · ${p.type==='experiment'?'실험':'본'}</option>`).join('');const e=entry();if(data.projects.some(p=>p.id===e.projectId))sel.value=e.projectId;$('#projectList').innerHTML=data.projects.map(p=>`<div class="project-item ${p.type}"><span class="badge">${p.type==='experiment'?'의미 유예':'본 프로젝트'}</span><div><b>${escapeHtml(p.name)}</b><small>${p.type==='experiment'?'7일 · 60% 완성에서 판단':'지속 운영 · 검증과 개선'}</small></div>${data.projects.length>1?`<button data-delete-project="${p.id}" aria-label="삭제">×</button>`:''}</div>`).join('')}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const fields=['focusMinutes','started','oneLine','learned','blocked','solved','nevertheless','aiHelp','tomorrowFirst','independence','motivation','projectId'];
function renderActions(){const e=entry(),actions=e.actions||[];$('#actionList').innerHTML=actions.length?actions.map((a,i)=>`<div class="action-row ${i===0?'primary-action':''}" data-action-id="${a.id}"><input class="action-check" type="checkbox" ${a.done?'checked':''} aria-label="${i===0?'핵심 행동':'추가 행동'} 완료" /><input class="action-text" type="text" maxlength="120" value="${escapeHtml(a.text)}" placeholder="${i===0?'오늘 가장 중요한 행동':'추가로 한 일'}" /><span class="action-tools">${i===0?'<span class="action-label">핵심</span>':''}<button type="button" class="move-action" aria-label="다른 날짜로 이동" title="다른 날짜로 이동">↗</button>${i===0?'':`<button type="button" class="delete-action" aria-label="행동 삭제">×</button>`}</span></div>`).join(''):`<div class="action-row primary-action" data-action-id="${crypto.randomUUID()}"><input class="action-check" type="checkbox" aria-label="핵심 행동 완료" /><input class="action-text" type="text" maxlength="120" placeholder="예: 로그인 화면의 입력창 하나 만들기" /><span class="action-tools"><span class="action-label">핵심</span><button type="button" class="move-action" aria-label="다른 날짜로 이동" title="다른 날짜로 이동">↗</button></span></div>`}
function hydrate(){const e=entry();fields.forEach(id=>{const el=$('#'+id);if(!el)return;if(el.type==='checkbox')el.checked=!!e[id];else el.value=e[id]??''});$$('[name=workMode]').forEach(x=>x.checked=x.value===(e.workMode||'solo'));$$('[name=mood]').forEach(x=>x.checked=Number(x.value)===Number(e.mood));renderActions();renderReturn()}
function readActions(){return $$('.action-row').map((row,i)=>({id:row.dataset.actionId||crypto.randomUUID(),text:row.querySelector('.action-text').value.trim(),done:row.querySelector('.action-check').checked})).filter((a,i)=>i===0||a.text)}
function collect(){const old=entry(),wasStarted=old.started;const e={...old};fields.forEach(id=>{const el=$('#'+id);e[id]=el.type==='checkbox'?el.checked:el.value});e.actions=readActions();e.keyAction=e.actions[0]?.text||'';e.completed=!!e.actions[0]?.done;e.mood=Number($('[name=mood]:checked')?.value)||null;e.focusMinutes=Number(e.focusMinutes)||0;e.independence=e.independence?Number(e.independence):null;e.motivation=e.motivation?Number(e.motivation):null;e.workMode=$('[name=workMode]:checked').value;e.updatedAt=new Date().toISOString();if(e.started&&!wasStarted&&selectedDate===todayKey()){e.startedAt=e.startedAt||new Date().toISOString();completeRecovery(e.startedAt)}data.entries[selectedDate]=e;save();renderSummary()}
function completeRecovery(at){const open=[...data.interruptions].reverse().find(x=>!x.recoveredAt);if(open){open.recoveredAt=at;const hours=(new Date(at)-new Date(open.at))/36e5;data.recoveries.push({interruptedAt:open.at,recoveredAt:at,hours:+hours.toFixed(1)})}}
function streak(){let n=0;for(let i=0;i>-366;i--){const e=data.entries[dateOffset(i)];if(e?.started)n++;else if(i===0)continue;else break}return n}
function renderSummary(){const s=streak();$('#heroStreak').textContent=s;$('#dashStreak').textContent=s+'일'}
function toggleTimer(){if(!$('.action-text')?.value.trim()){toast('먼저 오늘의 핵심 행동을 적어주세요.');$('.action-text')?.focus();return}if(!timer.running){timer.running=true;timer.startedAt=Date.now();$('#timerBtn').textContent='잠시 멈춤';$('#started').checked=true;collect();timer.id=setInterval(tick,1000);toast('좋아요. 10분만 시작합니다.')}else{clearInterval(timer.id);timer.running=false;$('#timerBtn').textContent='계속하기';addElapsed()}}
function addElapsed(){if(!timer.startedAt)return;const mins=Math.max(1,Math.round((Date.now()-timer.startedAt)/60000));$('#focusMinutes').value=(Number($('#focusMinutes').value)||0)+mins;timer.startedAt=null;collect()}
function tick(){timer.remaining--;renderTimer();if(timer.remaining<=0){clearInterval(timer.id);timer.running=false;addElapsed();$('#timerBtn').textContent='10분 더';timer.remaining=600;renderTimer();toast('10분을 해냈어요. 멈춰도, 더 해도 충분합니다.');if('Notification'in window&&Notification.permission==='granted')new Notification('10분 완료',{body:'시작했다는 증거를 만들었습니다.'})}}
function renderTimer(){const m=Math.floor(timer.remaining/60),s=timer.remaining%60;$('#timerDisplay').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function renderDashboard(){const days=Array.from({length:7},(_,i)=>dateOffset(i-6)),entries=days.map(d=>data.entries[d]||{date:d});const starts=entries.filter(e=>e.started).length,completes=entries.filter(e=>e.completed).length,total=entries.reduce((a,e)=>a+(Number(e.focusMinutes)||0),0);$('#startRate').textContent=Math.round(starts/7*100)+'%';$('#completeRate').textContent=(starts?Math.round(completes/starts*100):0)+'%';$('#totalFocus').textContent=total>=60?`${Math.floor(total/60)}h ${total%60}m`:`${total}m`;$('#startRateDelta').textContent=`${starts}일 시작 · 7일 기준`;const max=Math.max(30,...entries.map(e=>e.focusMinutes||0));$('#weekChart').innerHTML=entries.map(e=>{const d=new Date(e.date+'T12:00');return `<div class="day-col ${e.started?'started':''}"><div class="bar-wrap" title="${e.focusMinutes||0}분"><i class="bar" style="height:${Math.max(2,(e.focusMinutes||0)/max*100)}%"></i></div><b>${d.toLocaleDateString('ko-KR',{weekday:'short'})}</b><span>${e.focusMinutes||0}분</span></div>`}).join('');renderSpark(entries);renderMood(entries);renderRecoveries();const solo=entries.filter(e=>e.started&&e.workMode==='solo').length,together=entries.filter(e=>e.started&&e.workMode==='together').length,den=Math.max(1,solo+together);$('#soloCount').textContent=solo+'일';$('#togetherCount').textContent=together+'일';$('#soloBar').style.width=solo/den*100+'%';$('#togetherBar').style.width=together/den*100+'%'}
function renderSpark(entries){const vals=entries.map(e=>e.independence||null),valid=vals.filter(Boolean);$('#independenceAvg').textContent=valid.length?(valid.reduce((a,b)=>a+b,0)/valid.length).toFixed(1)+'/5':'—';if(!valid.length){$('#independenceTrend').innerHTML='<p class="gentle">기록이 쌓이면 추세가 보입니다.</p>';return}const pts=vals.map((v,i)=>`${i*100/6},${120-(v||1)*22}`).join(' ');$('#independenceTrend').innerHTML=`<svg viewBox="0 0 100 125" preserveAspectRatio="none"><line x1="0" y1="98" x2="100" y2="98" stroke="#e5e5df"/><line x1="0" y1="32" x2="100" y2="32" stroke="#e5e5df"/><polyline points="${pts}" fill="none" stroke="#1f6b5d" stroke-width="3" vector-effect="non-scaling-stroke" stroke-linecap="round"/></svg>`}
function renderMood(entries){const emoji=['','😞','😕','😐','🙂','😊'],valid=entries.map(e=>Number(e.mood)||null).filter(Boolean);$('#moodAvg').textContent=valid.length?emoji[Math.round(valid.reduce((a,b)=>a+b,0)/valid.length)]+' '+(valid.reduce((a,b)=>a+b,0)/valid.length).toFixed(1):'—';$('#moodTrend').innerHTML=entries.map(e=>{const d=new Date(e.date+'T12:00'),m=Number(e.mood)||0;return `<div class="mood-day"><i style="height:${m?m*19:8}px">${m?emoji[m]:''}</i><span>${d.toLocaleDateString('ko-KR',{weekday:'short'})}</span></div>`}).join('')}
function renderRecoveries(){const rows=data.recoveries.slice(-3).reverse();$('#recoveryLatest').textContent=rows.length?formatHours(rows[0].hours):'—';$('#recoveryList').innerHTML=rows.length?rows.map(r=>`<div class="recovery-item"><span>${new Date(r.recoveredAt).toLocaleDateString('ko-KR',{month:'short',day:'numeric'})} 복귀</span><b>${formatHours(r.hours)}</b></div>`).join(''):'<p class="gentle">중단을 표시하고 다시 시작하면 복귀시간이 기록됩니다.</p>'}
function formatHours(h){if(h<1)return Math.round(h*60)+'분';if(h<24)return h.toFixed(h<10?1:0)+'시간';return (h/24).toFixed(1)+'일'}
function renderReturn(){const open=[...data.interruptions].reverse().find(x=>!x.recoveredAt);if(!open){$('#returnBtn').classList.add('hidden');return}const h=(Date.now()-new Date(open.at))/36e5;$('#returnTitle').textContent=`멈춘 지 ${formatHours(h)}`;$('#returnCopy').textContent='지금 돌아오면 이 시간이 복귀 기록이 됩니다. 완벽한 재시작은 필요 없습니다.';$('#returnBtn').classList.remove('hidden')}
function renderCycle(){const start=new Date(data.cycle.start+'T12:00'),now=new Date(),week=Math.max(1,Math.min(12,Math.floor((now-start)/6048e5)+1));$('#cycleGoal').value=data.cycle.goal||'';$('#cycleStart').value=data.cycle.start;$('#cycleProgress').style.width=week/12*100+'%';$('#cycleText').textContent=`${week}주차 / 12주`;$('#weekDots').innerHTML=Array.from({length:12},(_,i)=>`<i class="${i+1<week?'done':i+1===week?'current':''}" title="${i+1}주차"></i>`).join('')}
function renderBackupSummary(){const dates=Object.values(data.entries).filter(e=>(e.actions||[]).some(a=>a.text)||e.keyAction||e.oneLine).length,actions=Object.values(data.entries).reduce((n,e)=>n+(e.actions||[]).filter(a=>a.text).length,0);$('#backupSummary').textContent=`현재 누적 기록: ${dates}일 · 행동 ${actions}개`}
function nav(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='dashboard')renderDashboard();if(view==='system'){renderProjects();renderCycle();renderBackupSummary()}scrollTo(0,0)}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.view)));fields.forEach(id=>$('#'+id)?.addEventListener('change',collect));$$('[name=workMode]').forEach(x=>x.addEventListener('change',collect));$('#dailyForm').addEventListener('submit',e=>{e.preventDefault();collect();toast('오늘의 증거를 저장했습니다.')});$('#timerBtn').addEventListener('click',toggleTimer);$('#timerReset').addEventListener('click',()=>{clearInterval(timer.id);timer={remaining:600,running:false,id:null,startedAt:null};renderTimer();$('#timerBtn').textContent='10분 시작'});
let movingActionId=null;
$('#actionList').addEventListener('change',collect);$('#actionList').addEventListener('input',collect);$('#actionList').addEventListener('click',e=>{const row=e.target.closest('.action-row');if(!row)return;if(e.target.classList.contains('delete-action')){row.remove();collect();toast('행동을 삭제했습니다.');return}if(e.target.classList.contains('move-action')){collect();movingActionId=row.dataset.actionId;const action=entry().actions.find(a=>a.id===movingActionId);if(!action?.text){toast('옮길 행동 내용을 먼저 적어주세요.');return}$('#moveActionName').textContent=action.text;$('#moveActionDate').value=selectedDate;$('#moveActionDialog').showModal()}});$('#addActionBtn').addEventListener('click',()=>{collect();const e=entry();e.actions.push({id:crypto.randomUUID(),text:'',done:false});data.entries[selectedDate]=e;save();renderActions();const inputs=$$('.action-text');inputs[inputs.length-1].focus()});$$('[name=mood]').forEach(x=>x.addEventListener('change',collect));
function closeMoveDialog(){movingActionId=null;$('#moveActionDialog').close()}
$('#closeMoveDialog').addEventListener('click',closeMoveDialog);$('#cancelMoveAction').addEventListener('click',closeMoveDialog);$('#moveActionForm').addEventListener('submit',e=>{e.preventDefault();const target=$('#moveActionDate').value;if(!target||target===selectedDate){toast(target===selectedDate?'이미 이 날짜에 있습니다.':'날짜를 선택해주세요.');return}collect();const source=entry(),index=source.actions.findIndex(a=>a.id===movingActionId);if(index<0){closeMoveDialog();return}const [action]=source.actions.splice(index,1);source.keyAction=source.actions[0]?.text||'';source.completed=!!source.actions[0]?.done;source.updatedAt=new Date().toISOString();const destination=entryFor(target);destination.actions=[...(destination.actions||[]),action];destination.keyAction=destination.actions[0]?.text||'';destination.completed=!!destination.actions[0]?.done;destination.updatedAt=new Date().toISOString();data.entries[selectedDate]=source;data.entries[target]=destination;save();renderActions();renderCalendar();closeMoveDialog();toast(`${new Date(target+'T12:00').toLocaleDateString('ko-KR',{month:'long',day:'numeric'})}로 옮겼습니다.`)});
function closeMoveDayDialog(){$('#moveDayDialog').close()}
$('#moveDayBtn').addEventListener('click',()=>{collect();const e=entry();if(!hasDayContent(e)){toast('이 날짜에는 옮길 기록이 없습니다.');return}const actionCount=(e.actions||[]).filter(a=>a.text).length;$('#moveDaySummary').textContent=`${new Date(selectedDate+'T12:00').toLocaleDateString('ko-KR')} · 행동 ${actionCount}개와 돌아보기 기록`;$('#moveDayDate').value=selectedDate;$('#moveDayDialog').showModal()});$('#closeMoveDayDialog').addEventListener('click',closeMoveDayDialog);$('#cancelMoveDay').addEventListener('click',closeMoveDayDialog);$('#moveDayForm').addEventListener('submit',e=>{e.preventDefault();const target=$('#moveDayDate').value;if(!target||target===selectedDate){toast(target===selectedDate?'현재 기록과 같은 날짜입니다.':'날짜를 선택해주세요.');return}if(timer.running)toggleTimer();collect();const sourceDate=selectedDate,source=structuredClone(entry()),destination=data.entries[target];data.entries[target]=mergeWholeDay(destination,source,target);delete data.entries[sourceDate];selectedDate=target;calendarMonth=new Date(target+'T12:00');save();renderDate();renderProjects();hydrate();renderSummary();closeMoveDayDialog();toast('행동과 돌아보기 전체 기록을 옮겼습니다.')});
$('#prevDate').addEventListener('click',()=>moveDate(-1));$('#nextDate').addEventListener('click',()=>moveDate(1));$('#goToday').addEventListener('click',()=>changeDate(todayKey()));$('#calendarToggle').addEventListener('click',()=>{$('#calendarPanel').classList.toggle('hidden');renderCalendar()});$('#prevMonth').addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()-1);renderCalendar()});$('#nextMonth').addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()+1);renderCalendar()});$('#calendarGrid').addEventListener('click',e=>{const key=e.target.dataset.date;if(key)changeDate(key)});document.addEventListener('click',e=>{if(!e.target.closest('.date-nav')&&!e.target.closest('#calendarPanel'))$('#calendarPanel').classList.add('hidden')});
$('#interruptBtn').addEventListener('click',()=>{if(confirm('지금 중단으로 표시할까요? 다시 시작할 때까지의 시간이 기록됩니다.')){data.interruptions.push({at:new Date().toISOString(),recoveredAt:null});save();renderReturn();toast('중단을 기록했습니다. 돌아오면 이어가요.')}});$('#returnBtn').addEventListener('click',()=>{const at=new Date().toISOString();completeRecovery(at);$('#started').checked=true;collect();save();renderReturn();toast('돌아왔습니다. 복귀 자체가 성장입니다.')});
$('#addProjectBtn').addEventListener('click',()=>$('#projectDialog').showModal());$('#createProject').addEventListener('click',e=>{const name=$('#newProjectName').value.trim();if(!name){e.preventDefault();return}const type=$('[name=projectType]:checked').value;data.projects.push({id:crypto.randomUUID(),name,type,created:todayKey()});save();renderProjects();$('#newProjectName').value='';toast('프로젝트를 추가했습니다.')});$('#projectList').addEventListener('click',e=>{const id=e.target.dataset.deleteProject;if(id&&confirm('이 프로젝트를 목록에서 지울까요? 기존 일일 기록은 유지됩니다.')){data.projects=data.projects.filter(p=>p.id!==id);save();renderProjects()}});
async function exportBackup(){collect();const filename=`다시시작-전체백업-${todayKey()}.json`,content=JSON.stringify(data,null,2),blob=new Blob([content],{type:'application/json'});if('showSaveFilePicker'in window){try{const handle=await window.showSaveFilePicker({suggestedName:filename,types:[{description:'다시, 시작 백업 파일',accept:{'application/json':['.json']}}]});const writable=await handle.createWritable();await writable.write(blob);await writable.close();toast('선택한 위치에 전체 백업을 저장했습니다.');return}catch(error){if(error.name==='AbortError')return}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();URL.revokeObjectURL(a.href);toast('브라우저의 다운로드 위치에 전체 백업을 저장했습니다.')}
async function importBackups(files){if(!files.length)return;try{let merged=data;for(const file of files){const parsed=JSON.parse(await file.text());if(!parsed.entries||!parsed.projects)throw Error();merged=mergeData(merged,parsed)}data=merged;save();renderProjects();hydrate();renderDate();renderBackupSummary();toast(`${files.length}개 백업을 현재 기록과 합쳤습니다.`)}catch{toast('올바른 백업 파일이 아닙니다.')}}
async function chooseBackupFiles(){if('showOpenFilePicker'in window){try{const handles=await window.showOpenFilePicker({multiple:true,types:[{description:'다시, 시작 백업 파일',accept:{'application/json':['.json']}}]});const files=await Promise.all(handles.map(handle=>handle.getFile()));await importBackups(files);return}catch(error){if(error.name==='AbortError')return}}$('#importInput').click()}
$('#cycleGoal').addEventListener('change',e=>{data.cycle.goal=e.target.value;save()});$('#cycleStart').addEventListener('change',e=>{data.cycle.start=e.target.value||todayKey();save();renderCycle()});$('#exportBtn').addEventListener('click',exportBackup);$('#importBtn').addEventListener('click',chooseBackupFiles);$('#importInput').addEventListener('change',async e=>{await importBackups([...e.target.files]);e.target.value=''});$('#clearBtn').addEventListener('click',()=>{if(confirm('모든 기록을 이 기기에서 지울까요? 이 작업은 되돌릴 수 없습니다.')){localStorage.removeItem(KEY);location.reload()}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').classList.add('hidden')}});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderDate();renderProjects();hydrate();renderSummary();renderCycle();renderBackupSummary();
